### ISSUE TITLE
Revision items to complete

### ISSUE THREAD

**Issue by dicook** [srkobakian/algorithm#4]
- [x] Where did the thyroid data get downloaded from? We should make it clear that this is publicly available.
- [ ] Need a choropleth and a hexagon map of Tasmania to finish off the implementation section now
- [x] There's a lower case "figure" somewhere that needs to be upper case
- [x] Algorithm diagram not showing in html
- [x] Should Steff's email be changed to a gmail?

**Comment by dicook** [comment]
Hi @srkobakian I think we can skip the second point above. I'm happy with the changes and the response. Can you re-submit it?

**Comment by srkobakian** [comment]
Fantastic, thank you Di
